#!/usr/bin/env groovy
pipeline {
    agent {
        docker {
            image 'node:6-alpine'
            args '-p 3000:3000'
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            environment {
                AN_ACCESS_KEY = credentials('4baa3bcb-b431-4728-8b2a-27abfea2bbfb')
            }
            steps {
                sh 'npm install'
                // echo 'trying'
                sh 'echo "$AN_ACCESS_KEY"'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
    }
}
